### ISSUE TITLE
[Request] for an example of Unifi-Network-Application from linuxserver.io

### ISSUE THREAD

**Issue by Ciberbago** [Haxxnet/Compose-Examples#16]
**What FOSS project is currently missing. Provide names and links.**

* NAME: Unifi-Network-Application
* GitHub URL: https://github.com/linuxserver/docker-unifi-network-application

**Does an example docker-compose.yml exist?**

* [0] - Yes, managed by the FOSS maintainer. See links below.

It exists... but requires external mongodb and I don't have the required knowledge to do that. I would like a ready to use example please.

Here some links to pre-existing docker-compose examples:
- <[link1](https://github.com/linuxserver/docker-unifi-network-application)>
It's only on the readme section of the repo.

**Describe alternatives you've considered**
I've searched for someone with an example but it's too new and there are none.

**Additional context**
I know it's not FOSS, but currently I'm using unifi-controller from linuxserver.io but they say, they are going to deprecate that image. I need to be ready when the time comes.

**Comment by l4rm4nd** [comment]
Hi @Ciberbago,

thanks for reaching out.

The [documentation ](https://hub.docker.com/r/linuxserver/unifi-network-application) provided by Linuxserver is quite good. However, I understand where you are coming from. Adjusting the docker-compose.yml with a proper mongo db service is not that straight forward.

Nonetheless, I've done some research and crafted a (hopefully) working compose file:

````
---
version: "2.1"
services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi-db
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/unifi-network-application/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  unifi-db:
    image: mongo:4.4
    container_name: unifi-network-application-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=unifi-db
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/unifi-network-application/mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
````
Note that you are mounting a file named `init-mongo.js` into the mongo db container. This file is necessary to initialize the mongo database (see https://hub.docker.com/_/mongo/ at "Initializing a fresh instance"). It basically defines the database name and user credentials for the unifi-network-application container.

The file contains the following content:

````
db.getSiblingDB("unifi-db").createUser({user: "unifi", pwd: "unifi", roles: [{role: "readWrite", db: "unifi-db"}]});
db.getSiblingDB("unifi-db_stat").createUser({user: "unifi", pwd: "unifi", roles: [{role: "readWrite", db: "unifi-db_stat"}]});
````

These parameters are also referenced in the `docker-compose.yml` file above. So either leave as is or adjust everywhere accordingly. May have a try and give feedback whether my example works. 

As long as the given example is unconfirmed, I will not include it to this repository.
