### ISSUE TITLE
Paperless-ngx image (linuxserver) is deprecated

### ISSUE THREAD

**Issue by null-except** [Haxxnet/Compose-Examples#3]
**Describe the bug**
linuxserver stopped maintaining this image. 

**Expected behavior**
We might change for the official image : https://github.com/paperless-ngx/paperless-ngx

**Comment by null-except** [comment]
Something like this might be useful I guess : 

```
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /DIR/redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - /mnt/containers/adrien-paperless-ngx/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: adrien-paperless-ngx
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "PORT:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "URL:PORT"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /DIR/data:/usr/src/paperless/data
      - /DIR/media:/usr/src/paperless/media
      - /DIR/export:/usr/src/paperless/export
      - /DIR/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_URL: "URL"
      PAPERLESS_OCR_LANGUAGES: fra
      PAPERLESS_SECRET_KEY: 
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_OCR_LANGUAGE: fra

volumes:
  data:
  media:
  pgdata:
  redisdata:
```
