### ISSUE TITLE
IPsec VPN Server on Docker

### ISSUE THREAD

**Issue by hadalin** [Haxxnet/Compose-Examples#5]
**What FOSS project is currently missing. Provide names and links.**

* NAME: IPsec VPN Server on Docker
* GitHub URL: https://github.com/hwdsl2/docker-ipsec-vpn-server

**Does an example docker-compose.yml exist?**

* Yes, managed by the FOSS maintainer. See links below.

Here some links to pre-existing docker-compose examples:
- https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docker-compose.yml

Here my personal working docker-compose.yml:

````yml
version: '3'

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    environment:
      - VPN_IPSEC_PSK
      - VPN_USER
      - VPN_PASSWORD
      - VPN_ADDL_USERS
      - VPN_ADDL_PASSWORDS
      - VPN_DNS_SRV1
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
      
volumes:
  data:
````
